### ISSUE TITLE
Error when building JPACKAGE 

### ISSUE THREAD

**Issue by ghost** [beryx-gist/badass-runtime-example#3] opened 2021-09-04 14:30 UTC
I am using Mac. If I create jpackage. It comes an error like this `Bundler Mac PKG Package skipped because of a configuration problem: "Missing --main-jar parameter for non modular application"`

**Comment by siordache** [comment] 2021-09-04 18:37
Configure the build to create only `dmg` installers for Mac:
https://github.com/beryx-gist/badass-runtime-example/blob/411c984541a762a97005346b94ce81b0f3e4df63/build.gradle#L33-L44

**Comment by ghost** [comment] 2021-09-05 11:34
logback.xml file missing in JPACKAGE.

**Comment by siordache** [comment] 2021-09-05 13:02
Duplicate of #1

**Closed as completed by siordache** 2021-09-05 13:02 UTC
