### ISSUE TITLE
logback.xml missing in JPACKAGE.

### ISSUE THREAD

**Issue by ghost** [beryx-gist/badass-runtime-example#2] opened 2021-09-03 15:51 UTC
How to copy the files to jpackage?

**Comment by siordache** [comment] 2021-09-03 15:59
https://github.com/beryx-gist/badass-runtime-example/blob/01908dda7cd94c178fc727547cf50ca8ef069bae/build.gradle#L43-L48

**Comment by ghost** [comment] 2021-09-04 01:11
@siordache this code not worked.

**Comment by siordache** [comment] 2021-09-04 10:13
See https://github.com/beryx-gist/badass-runtime-example/issues/1#issuecomment-912947566

**Comment by ghost** [comment] 2021-09-04 13:56
@siordache I tried but file missing in jpackage.

**Comment by siordache** [comment] 2021-09-04 18:40
There was still a problem:
https://github.com/beryx-gist/badass-runtime-example/issues/1#issuecomment-913019118

**Comment by ghost** [comment] 2021-09-05 01:05
@siordache I tried but same issue

**Comment by siordache** [comment] 2021-09-05 13:02
Duplicate of #1

**Closed as completed by siordache** 2021-09-05 13:02 UTC
